x = msgBox("Our Model is a boat with a net.",0,"Introduction")
Set shell = createobject("WScript.Shell")
shell.run "https://csg.tinkercad.com/things/0w7qcl6cbtr/t725.png?rev=1642531052978000000&s=&v=1"
CreateObject("WScript.Shell").Run("Test.bat")
x = msgBox("We use energy from the sun to power a boat, which is attached to a net.",0,"Presentation")
x = msgBox("The net will catch trash floating in bodies of water.",0,"Presentation")
x = msgBox("We noticed that trash was floating in bodies of water and we couldn't clean trash in bodies of water by ourselves, that wouldn't be effiecent enough.",0,"Presentation")
x = msgBox("We improved our design by using the sun's power instead of the energy of the human body",0,"Presentation")
x = msgBox("We did this for marine ecosystems, and everyone, most beings depend on water. We are made 70% of it too",0,"Presentation")
x = msgBox("Our Problem is trash under the ocean, This falls under 2 SDGs, 14-Life Below Water, 6-Clean Water and Sanitation.",0,"Presentation")
x = msgBox("We did some searching on the EPA website of our problem",0,"Presentation")
x = msgBox("We used TinkerCAD to model our problem",0,"Presentation")
x = msgBox("Our prototypes are, a picture of a TinkerCAD model, which I think you have seen, but here it is again",0,"Presentation")
shell.run "https://csg.tinkercad.com/things/0w7qcl6cbtr/t725.png?rev=1642531052978000000&s=&v=1"
x = msgBox("We weren't able to get a physical model just yet, we tried 3D printing but it kept giving us errors, so I don't have one yet",0,"Presentation")
x = msgBox("Next time I would try something else than 3D printing, I learned that it is very hard to find solutions to clean up trash from oceans.",0,"Presentation")
x = msgBox("The End",0,"End")
